// ─────────────────────────────────────────────
// AccessPilot Constants
// Single source of truth for labels, colors, mock data
// ─────────────────────────────────────────────

// Severity configuration
// Used by Badge.js, ViolationList.js, ScoreCard.js
export const SEVERITY = {
  critical: {
    label:   'Critical',
    color:   '#dc2626',
    bg:      '#fff1f2',
    border:  '#fecaca',
    text:    '#b91c1c',
    darkBg:  '#450a0a',
    darkText:'#fca5a5',
    weight:   4,          // Score penalty weight
    icon:    '🔴',
  },
  serious: {
    label:   'Serious',
    color:   '#ea580c',
    bg:      '#fff7ed',
    border:  '#fed7aa',
    text:    '#c2410c',
    darkBg:  '#431407',
    darkText:'#fdba74',
    weight:   3,
    icon:    '🟠',
  },
  moderate: {
    label:   'Moderate',
    color:   '#ca8a04',
    bg:      '#fefce8',
    border:  '#fef08a',
    text:    '#a16207',
    darkBg:  '#422006',
    darkText:'#fde047',
    weight:   2,
    icon:    '🟡',
  },
  minor: {
    label:   'Minor',
    color:   '#16a34a',
    bg:      '#f0fdf4',
    border:  '#bbf7d0',
    text:    '#15803d',
    darkBg:  '#052e16',
    darkText:'#86efac',
    weight:   1,
    icon:    '🟢',
  },
}

// Agent names and icons for the timeline
export const AGENTS = [
  {
    key:         'scanner',
    name:        'Scanner Agent',
    description: 'Loading page and running WCAG audit with axe-core',
    icon:        '🔍',
    color:       '#3366f4',
  },
  {
    key:         'reasoning',
    name:        'Reasoning Agent',
    description: 'Analysing violations — classifying severity and user impact',
    icon:        '🧠',
    color:       '#7c3aed',
  },
  {
    key:         'fix',
    name:        'Fix Agent',
    description: 'Generating HTML and ARIA fixes for each violation',
    icon:        '🔧',
    color:       '#0891b2',
  },
  {
    key:         'coach',
    name:        'Coach Agent',
    description: 'Building your personalised accessibility action plan',
    icon:        '🎯',
    color:       '#059669',
  },
]

// Filter tabs for ViolationList
export const FILTER_TABS = [
  { key: 'all',      label: 'All Issues' },
  { key: 'critical', label: 'Critical'   },
  { key: 'serious',  label: 'Serious'    },
  { key: 'moderate', label: 'Moderate'   },
  { key: 'minor',    label: 'Minor'      },
]

// ─────────────────────────────────────────────
// MOCK DATA
// Used by the frontend during Phase 2 development
// (before the backend is ready in Phase 3)
// Replace with real API data in Phase 4
// ─────────────────────────────────────────────
export const MOCK_SCAN_RESULT = {
  scanId:     'ap-mock-001',
  url:        'https://example.com',
  pageTitle:  'Example Domain',
  timestamp:  new Date().toISOString(),
  score:      62,

  summary: {
    total:      12,
    critical:    3,
    serious:     4,
    moderate:    3,
    minor:       2,
    passes:     38,
    incomplete:  5,
  },

  agentTimeline: [
    { agent: 'Scanner',   status: 'complete', durationMs: 3100, message: 'Found 12 violations across 38 passing rules' },
    { agent: 'Reasoning', status: 'complete', durationMs: 4800, message: 'Classified and explained all 12 issues'       },
    { agent: 'Fix',       status: 'complete', durationMs: 6200, message: 'Generated HTML and ARIA fixes'                },
    { agent: 'Coach',     status: 'complete', durationMs: 2600, message: 'Built your accessibility action plan'         },
  ],

  violations: [
    {
      id:          'image-alt',
      description: 'Images must have alternate text',
      htmlSnippet: '<img src="hero.jpg" class="hero-image">',
      severity:    'critical',
      wcagRef:     'WCAG 2.1 — 1.1.1 Non-text Content',
      wcagLevel:   'Level A',
      userImpact:  'Screen reader users receive no information about this image. Blind users navigating with JAWS or NVDA will hear the filename or nothing at all.',
      explanation: 'This image has no alt attribute. Screen readers require alt text to announce what the image conveys to non-sighted users.',
      fixedHTML:   '<img src="hero.jpg" class="hero-image" alt="Team working on accessibility improvements">',
      ariaFix:     'If this image is purely decorative, use alt="" to instruct screen readers to skip it entirely.',
      recommendation: 'Add descriptive alt text to every meaningful image. Use alt="" for decorative images.',
      coachTip:    'Ask yourself: if this image disappeared, what information would a sighted user lose? Write that as your alt text.',
    },
    {
      id:          'color-contrast',
      description: 'Elements must have sufficient colour contrast',
      htmlSnippet: '<p class="subtitle" style="color: #aaa; background: #fff;">Welcome to our site</p>',
      severity:    'serious',
      wcagRef:     'WCAG 2.1 — 1.4.3 Contrast (Minimum)',
      wcagLevel:   'Level AA',
      userImpact:  'Users with low vision or colour blindness cannot read this text. The contrast ratio is 2.3:1 — the minimum required is 4.5:1.',
      explanation: 'The text colour (#aaa) on the white background (#fff) does not meet WCAG AA contrast requirements.',
      fixedHTML:   '<p class="subtitle" style="color: #6b7280; background: #fff;">Welcome to our site</p>',
      ariaFix:     'No ARIA fix needed — this is a CSS colour issue. Update the text colour to achieve a 4.5:1 contrast ratio.',
      recommendation: 'Use a colour contrast checker (e.g. WebAIM Contrast Checker) when choosing text and background colour pairs.',
      coachTip:    'A quick rule: if you squint and the text becomes hard to read, the contrast is probably insufficient.',
    },
    {
      id:          'label',
      description: 'Form elements must have labels',
      htmlSnippet: '<input type="email" placeholder="Enter email" class="email-field">',
      severity:    'critical',
      wcagRef:     'WCAG 2.1 — 1.3.1 Info and Relationships',
      wcagLevel:   'Level A',
      userImpact:  'Screen reader users cannot identify the purpose of this form field. The placeholder disappears on focus, leaving the field completely unlabelled.',
      explanation: 'This input element has no associated label element, aria-label, or aria-labelledby attribute.',
      fixedHTML:   '<label for="email-field">Email address</label>\n<input type="email" id="email-field" placeholder="Enter email" class="email-field">',
      ariaFix:     'Alternative: <input type="email" aria-label="Email address" placeholder="Enter email" class="email-field">',
      recommendation: 'Every form input needs a visible label. Never rely on placeholder text alone — it disappears when the user types.',
      coachTip:    'Labels are not optional extras — they are the primary way screen reader users understand what a field is for.',
    },
    {
      id:          'button-name',
      description: 'Buttons must have discernible text',
      htmlSnippet: '<button class="icon-btn"><svg><!-- search icon --></svg></button>',
      severity:    'critical',
      wcagRef:     'WCAG 2.1 — 4.1.2 Name, Role, Value',
      wcagLevel:   'Level A',
      userImpact:  'Screen reader users hear "button" with no indication of its purpose. They cannot know this is a search button.',
      explanation: 'This button contains only an SVG icon with no text, aria-label, or aria-labelledby.',
      fixedHTML:   '<button class="icon-btn" aria-label="Search the site"><svg aria-hidden="true"><!-- search icon --></svg></button>',
      ariaFix:     'Add aria-hidden="true" to the SVG so screen readers do not attempt to read the icon paths.',
      recommendation: 'All interactive elements need accessible names. Icon-only buttons always need aria-label.',
      coachTip:    'Every button should answer the question "what does this do?" — even when there is no visible text.',
    },
    {
      id:          'heading-order',
      description: 'Heading levels should only increase by one',
      htmlSnippet: '<h1>Page Title</h1>\n<h3>Section Title</h3>',
      severity:    'moderate',
      wcagRef:     'WCAG 2.1 — 1.3.1 Info and Relationships',
      wcagLevel:   'Level A',
      userImpact:  'Screen reader users navigate pages by jumping between headings. Skipping from h1 to h3 creates a gap that breaks the document outline.',
      explanation: 'Heading levels jump from h1 to h3, skipping h2. This disrupts the logical structure of the page.',
      fixedHTML:   '<h1>Page Title</h1>\n<h2>Section Title</h2>',
      ariaFix:     'No ARIA fix needed. Use the correct heading level in your HTML.',
      recommendation: 'Think of headings as a table of contents. They should nest logically: h1 → h2 → h3, never skipping a level.',
      coachTip:    'Use browser DevTools to inspect your page outline. It should read like the chapters of a well-organised book.',
    },
    {
      id:          'link-name',
      description: 'Links must have discernible text',
      htmlSnippet: '<a href="/about">Click here</a>',
      severity:    'serious',
      wcagRef:     'WCAG 2.1 — 2.4.4 Link Purpose (In Context)',
      wcagLevel:   'Level A',
      userImpact:  'Screen reader users who navigate by links hear a list of "click here" links with no context. They cannot tell where each link goes.',
      explanation: '"Click here" is not descriptive. Screen readers can list all links on a page — vague link text makes navigation impossible.',
      fixedHTML:   '<a href="/about">Learn about our accessibility mission</a>',
      ariaFix:     'If you cannot change the visible text: <a href="/about" aria-label="Learn about our accessibility mission">Click here</a>',
      recommendation: 'Link text should describe the destination, not the action. Avoid "click here", "read more", "learn more" without context.',
      coachTip:    'Read only your link texts aloud, in isolation. Do they tell you where you\'ll end up? If not, rewrite them.',
    },
    {
      id:          'document-title',
      description: 'Documents must have a title element',
      htmlSnippet: '<head>\n  <meta charset="UTF-8">\n  <!-- No <title> element -->\n</head>',
      severity:    'serious',
      wcagRef:     'WCAG 2.1 — 2.4.2 Page Titled',
      wcagLevel:   'Level A',
      userImpact:  'Screen reader users hear nothing when the page loads. Browser tabs show no title. Bookmark names are meaningless.',
      explanation: 'The page has no <title> element in its <head>. Every page must have a unique, descriptive title.',
      fixedHTML:   '<head>\n  <meta charset="UTF-8">\n  <title>About — AccessPilot Accessibility Demo</title>\n</head>',
      ariaFix:     'No ARIA fix needed. Add a <title> tag to your HTML <head>.',
      recommendation: 'Every page needs a unique, descriptive title. Format: "Page Name — Site Name".',
      coachTip:    'Your page title is the first thing a screen reader announces. Make it count.',
    },
    {
      id:          'html-lang',
      description: 'html element must have a lang attribute',
      htmlSnippet: '<html>\n  <head>...',
      severity:    'serious',
      wcagRef:     'WCAG 2.1 — 3.1.1 Language of Page',
      wcagLevel:   'Level A',
      userImpact:  'Screen readers cannot switch to the correct language pronunciation engine. Text may be read with the wrong accent or completely mispronounced.',
      explanation: 'The <html> element is missing the lang attribute. Screen readers use this to select the correct voice.',
      fixedHTML:   '<html lang="en">\n  <head>...',
      ariaFix:     'No ARIA fix needed. Add lang="en" (or the appropriate language code) to your root <html> element.',
      recommendation: 'Always add lang to your <html> element. For multilingual pages, add lang to individual sections too.',
      coachTip:    'Imagine reading a French novel but your screen reader is using an English voice. The lang attribute prevents exactly that.',
    },
    {
      id:          'focus-order',
      description: 'Focus order must be logical',
      htmlSnippet: '<div tabindex="5">Nav item 1</div>\n<div tabindex="3">Nav item 2</div>\n<div tabindex="8">Nav item 3</div>',
      severity:    'moderate',
      wcagRef:     'WCAG 2.1 — 2.4.3 Focus Order',
      wcagLevel:   'Level A',
      userImpact:  'Keyboard users experience a confusing, unpredictable tab order that jumps around the page.',
      explanation: 'Positive tabindex values create an explicit tab order that often conflicts with the visual reading order.',
      fixedHTML:   '<div>Nav item 1</div>\n<div>Nav item 2</div>\n<div>Nav item 3</div>',
      ariaFix:     'Remove explicit tabindex values. The browser\'s natural DOM order is almost always the correct tab order.',
      recommendation: 'Avoid positive tabindex values. Use tabindex="0" to make elements focusable, tabindex="-1" to exclude them.',
      coachTip:    'Tab through your own page from top to bottom. Does the focus move in the order you\'d expect? If not, reorganise your HTML or remove tabindex.',
    },
    {
      id:          'skip-link',
      description: 'Page should contain a skip navigation link',
      htmlSnippet: '<body>\n  <nav><!-- 40 nav links --></nav>\n  <main>Content here</main>',
      severity:    'moderate',
      wcagRef:     'WCAG 2.1 — 2.4.1 Bypass Blocks',
      wcagLevel:   'Level A',
      userImpact:  'Keyboard-only users must tab through every navigation link on every page load before reaching the main content.',
      explanation: 'There is no skip link to allow keyboard users to bypass the navigation and jump directly to the main content.',
      fixedHTML:   '<body>\n  <a href="#main-content" class="skip-link">Skip to main content</a>\n  <nav><!-- 40 nav links --></nav>\n  <main id="main-content">Content here</main>',
      ariaFix:     'No ARIA fix needed. The skip link is a standard HTML pattern.',
      recommendation: 'Add a "Skip to main content" link as the very first focusable element on every page. It can be visually hidden until focused.',
      coachTip:    'Try navigating your page using only Tab. How many keypresses before you reach the actual content? A skip link reduces that to one.',
    },
    {
      id:          'aria-required-children',
      description: 'ARIA roles must have required child roles',
      htmlSnippet: '<ul role="listbox">\n  <li>Option 1</li>\n  <li>Option 2</li>\n</ul>',
      severity:    'minor',
      wcagRef:     'WCAG 2.1 — 4.1.2 Name, Role, Value',
      wcagLevel:   'Level A',
      userImpact:  'Screen readers cannot correctly interpret the listbox widget because its children lack the required "option" role.',
      explanation: 'Elements with role="listbox" must contain elements with role="option". Plain <li> elements do not satisfy this requirement.',
      fixedHTML:   '<ul role="listbox">\n  <li role="option">Option 1</li>\n  <li role="option">Option 2</li>\n</ul>',
      ariaFix:     'Add role="option" to each <li> element inside the listbox.',
      recommendation: 'When using ARIA widget roles, always implement the full ARIA design pattern including required child roles and keyboard interaction.',
      coachTip:    'The ARIA Authoring Practices Guide (APG) at w3.org lists every ARIA widget and its required structure. Bookmark it.',
    },
    {
      id:          'autocomplete',
      description: 'Ensure form fields have autocomplete attributes',
      htmlSnippet: '<input type="tel" name="phone" placeholder="Phone number">',
      severity:    'minor',
      wcagRef:     'WCAG 2.1 — 1.3.5 Identify Input Purpose',
      wcagLevel:   'Level AA',
      userImpact:  'Users with cognitive disabilities and motor impairments cannot use browser autocomplete to fill in their phone number, requiring more manual effort.',
      explanation: 'This telephone input is missing the autocomplete attribute, which would allow browsers and assistive technologies to pre-fill it.',
      fixedHTML:   '<input type="tel" name="phone" autocomplete="tel" placeholder="Phone number">',
      ariaFix:     'No ARIA fix needed. Add the autocomplete attribute with the correct token.',
      recommendation: 'Add autocomplete attributes to all personal data fields (name, email, phone, address). Use the standard autocomplete token list from WCAG 1.3.5.',
      coachTip:    'autocomplete is not just a convenience — for users with motor disabilities who struggle to type, it can be the difference between completing a form or giving up.',
    },
  ],

  coachSummary: {
    overview:
      'Your site has 3 critical barriers that would prevent many disabled users from accessing your content. The highest-impact fixes are: adding alt text to images, labelling your form inputs, and adding accessible names to icon buttons. Together these 3 fixes would resolve your critical issues and push your score above 80.',
    priorityList: [
      'Add alt text to all images missing it (6 found)',
      'Label all unlabelled form inputs with <label> elements',
      'Add aria-label to all icon-only buttons',
      'Fix colour contrast on grey text — use #6b7280 minimum on white',
      'Add a "Skip to main content" skip link as the first focusable element',
    ],
    learningTips: [
      'Read WCAG 2.1 Level A success criteria — they are the non-negotiable baseline',
      'Install the axe DevTools browser extension for daily development feedback',
      'Test with a screen reader: NVDA on Windows (free) or VoiceOver on Mac (built-in)',
      'Run your pages through WebAIM\'s WAVE tool for a second opinion',
    ],
  },
}
